---
- hosts: all
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: "apt-get upgrade"
      apt:
        upgrade: yes
        cache_valid_time: 3600
    - name: "intall software-properties-common"
      become: yes
      apt:
        name: software-properties-common
        state: present
    - name: "add nodejs apt key"
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: "download node"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x bionic main
        update_cache: yes
    - name: "install node.js"
      apt:
        update_cache: yes
        name: nodejs
        state: present
    - name: "install apache2"
      apt:
        update_cache: yes
        name: apache2
        state: present
    - name: "enable apache2"
      shell: sudo a2enmod proxy | sudo a2enmod proxy_http
    - name: "Disable default Apache site"
      shell: sudo a2dissite 000-default.conf
    - name: "Copy new Apache site"
      shell: cp /home/ubuntu/env/jsapp-proxy.conf /etc/apache2/sites-available
    - name: "Enable default Apache site"
      shell: sudo a2ensite jsapp-proxy.conf
    - name: "Restart Apache server"
      shell: sudo systemctl reload apache2
    - name: "Create document root for domain configured in host variable"
      file:
        path: "/var/www/snake.game/html"
        state: directory
        owner: root
        group: root
        mode: "0755"
        recurse: true
    - name: "Copy Snake Game"
      shell: sudo cp -r /home/ubuntu/app/* /var/www/snake.game/html/
    - name: "Set up Apache virtualhost"
      template:
        src: /home/ubuntu/env/jsapp-proxy.conf
        dest: /etc/apache2/sites-available/
    - name: "Copy ID"
      shell: export DB_IP="mongodb://192.168.56.20/api/scores"
    - name: "Update Game.js with DB IP Address"
      shell: sudo sed -i "s/IP_ADDRESS/$(echo $DB_IP | sed 's#/#\\/#g')/" /var/www/snake.game/html/scripts/Game.js
