---
- hosts: all
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
    - name: "apt-get update"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: "apt-get upgrade"
      apt:
        upgrade: yes
        cache_valid_time: 3600
    - name: "intall software-properties-common"
      become: yes
      apt:
        name: software-properties-common
        state: present
    - name: "add nodejs apt key"
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: "download node"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x bionic main
        update_cache: yes
    - name: "install node.js"
      apt:
        update_cache: yes
        name: nodejs
        state: present
    - name: "add MONGODB apt key"
      apt_key:
        url: "https://www.mongodb.org/static/pgp/server-4.4.asc"
        state: present
    - name: "download MONGODB"
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
        update_cache: yes
    - name: "install MONGODB"
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
    - name: Start Mongo Service
      service:
        name: mongod
        state: started
    - name: "Enable MONGODB"
      service:
        name: mongod
        enabled: yes
    - name: Copy Mongo Config
      copy:
        src: /home/ubuntu/env/mongod.conf
        dest: /etc/mongod.conf
    - name: Restart Mongo Service
      service:
        name: mongod
        state: restarted
      become: true
    - name: Install Dependencies and Start DB
      shell: |
        npm install -g npm
        npm install -g forever
    - name: "Copy ID"
      shell: export DB_URI="mongodb://127.0.0.1:27017/snake"
